# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160916194808 on 2016-09-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfParse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
